#
# FIXME::REQUIRED: set an MLflow experiment name to track recipe executions and artifacts.
#
experiment:
  name: "ab1"
  tracking_uri: "sqlite:///metadata/mlflow/mlruns.db"
  artifact_location: "./metadata/mlflow/mlartifacts"
model_registry:
#
# FIXME::OPTIONAL: Set the registry server URI. This property is especially useful if you have a
#                  registry server that’s different from the tracking server.
#   uri: "sqlite:///metadata/mlflow/registry.db"
# FIXME::REQUIRED: Specifies the name of the Registered Model to use when registering a trained
#                  model to the MLflow Model Registry.
  model_name: "ab1_1"

SPLIT_RATIOS: [0.50, 0.23, 0.25]

INGEST_CONFIG:

  #using: parquet
  #location: "./data/sample.parquet"
  #using: "custom"
  #location: "data/taxi-fares.csv"
  #loader_method: read_csv_as_dataframe
  # FIXME::OPTIONAL: Specify the training and evaluation data location.
  # location: ""

  # For different options please read: https://github.com/mlflow/recipes-regression-template#ingest-step
  using: parquet
  location: "./data/sample.parquet"

INGEST_SCORING_CONFIG:
  using: parquet
  location: "./data/sample.parquet"
#   For different options please read: https://github.com/mlflow/recipes-regression-template#batch-scoring
#   FIXME::OPTIONAL: Specify the format of the scoring dataset. Natively supported formats are:
#                    parquet, spark_sql, delta.
#   using: ""
#   FIXME::OPTIONAL: Specify the scoring data location.
#   location: ""

PREDICT_OUTPUT_CONFIG:
  using: csv
  location: "./data/sample_output.csv"
# PREDICT_OUTPUT_CONFIG:
#   For different options please read: https://github.com/mlflow/recipes-regression-template#predict-step
#   FIXME::OPTIONAL: Specify the format of the scored dataset. Natively supported formats are:
#                    parquet, delta, table.
#   using: ""
#   FIXME::OPTIONAL: Specify the output location of the batch scoring predict step.
#   location: ""
